### ISSUE TITLE
There is no rating-delete-missing-itemid.txt in yelp

### ISSUE THREAD

**Issue by DebonairLi** [sunzhuntu/Recurrent-Knowledge-Graph-Embedding#19]
Hi,
In your data, there is no rating-delete-missing-itemid.txt in yelp.Could you please provide it?Thanks.

**Comment by sunzhuntu** [comment]
Actually, you may directly use the training and testing data. If I am not wrong, I remember we directly use that, since the dataset has been already pro-precessed before publishing.
